config/routes.rb
Rails.application.routes.draw do
  get 'location/show'

  get 'location' => 'location#show'

  get 'welcome/text'

  get 'welcome/index'

  get 'index' => 'welcome#index'

  post 'index' => 'welcome#index'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/location_controller.rb
class LocationController < ApplicationController
  
  def show
  		@location = Location.find(params[:id])
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

	def show
		@location = Location.find(params[:id])
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def text
  	response = HTTParty.get("http://api.wunderground.com/api/#{ENV['wunderground_api_key']}/conditions/q/OH/Columbus.json")
  	# @location = response['current_observation']['display_location']['full']
  	# @temperature = response['current_observation']['temperature_string']
  	@current_observation = response['current_observation']
  end

  def index
    @states = %w(HI AK CA OR WA ID UT NV AZ NM CO WY MT ND SD NB KS OK TX LA AR MO IA MN WI IL IN MI OH KY TN MS AL GA FL SC NC VA WV DE MD PA NY NJ CT RI MA VT NH ME DC).sort!

    if params[:city].present? && params[:state].present?
      city_param = URI.encode(params[:city])
      results = HTTParty.get("http://api.wunderground.com/api/#{ENV['wunderground_api_key']}/conditions/q/#{params[:state]}/#{city_param}.json")

      
      if results['response']['error'].present?
        @error = results['response']['error']['description']
      else
        @current_observation = results['current_observation']
        latitude = @current_observation['display_location']['latitude']
        longitude = @current_observation['display_location']['longitude']
        create_location(params[:city], params[:state], latitude, longitude)
      end
    end
    @locations = Location.all
  end

  def create_location(city_param, state_param, latitude, longitude)
    location_exists = false

    Location.all.each do |location| 
      if location.city == city_param && location.state == state_param
        location_exists = true
      end
    end
    if location_exists == false
      Location.create(city: city_param, state: state_param, latitude: latitude, longitude: longitude)
    end
  end



  # def index
  # 	@states = %w(HI AK CA OR WA ID UT NV AZ NM CO WY MT ND SD NB KS OK TX LA AR MO IA MN WI IL IN MI OH KY TN MS AL GA FL SC NC VA WV DE MD PA NY NJ CT RI MA VT NH ME DC).sort!
  		
  # 	@locations = Location.all
  			
  # 	results = HTTParty.get("http://api.wunderground.com/api/#{ENV['wunderground_api_key']}/conditions/q/#{params[:state]}/#{city_param}.json")
  # 		if results['response']['error'].present?
  # 			@error = results['response']['error']['description']

  # 		else
  # 			@current_observation = results['current_observation']
  # 			latitude = @current_observation['display_location']['latitude']
  # 			longitude = @current_observation['display_location']['longitude']

  #       location_exists = false
  #     if params[:city].present? && params[:state].present?
  #       Location.all.each do |location|   
  #         if location.city == params[:city] && location.state == params[:state] 
  #           location_exists = true 
  #         end
  #       end
  #     # end

  #     if location_exists == false 
  #         Location.create(
  #           city: params[:city],
  #           state: params[:state],
  #           latitude:latitude,
  #           longitude:longitude
  #             )
  #     end
  # 		end
  # 		end
  # 	end	
  end

  # city_param = URI.encode(params[:city])

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/location_helper.rb
module LocationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container">
    		<%= yield %>
	</div>
	
  </body>
</html>

app/views/location/show.html.erb
<h1>Location#show</h1>
<p>Find me in app/views/location/show.html.erb</p>
<div class="row">
	<div class="col-md-6">
		<h4><%= @location.city %>, <%= @location.state %></h4>
		<h5>Coordinates: <%= @location.latitude %>, <%= @location.longitude %></h5>
	</div>
</div>

<div class="row">
	<div class="col-md-6">
		<div id="location-map"></div>
	</div>
</div>

<%= javascript_tag do %>
	var longitude = <%= @location.longitude %>;
	var latitude = <%= @location.latitude %>;
<% end %>

<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['google_api_key'] %>&callback=initLocationMap"
    async defer></script>

app/views/locations/show.html.erb
<h1><%= @location.city %>, <%= @location.state %></h1>

<div class="row">
	<div class="col=md-6">
		<div id="location-map">

		</div>
	</div>
</div>

<script>
	var latitude = <%=@location.latitude%>;
	var longitude = <%=@location.longitude%>;
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['google_api_key'] %>&callback=cityMap"
    async defer></script>

app/views/welcome/index.html.erb
<div class="row">
	<div class="col-md-6">
		<div class="well">
			<h2>Look up your local forecast</h2>
			<%= form_tag index_path do %>
				<%= text_field_tag :city, nil, placeholder: "City" %>
				<%= select_tag :state, options_for_select(@states), prompt: "Please Select" %>
				<%= submit_tag "Check Weather", class: "btn btn-primary" %>
			<% end %>
		</div>
	</div>
</div>
<% if @error.present? %>
	<div class="row">
		<div class="col-md-6">
			<p><%= @error %></p>
		</div>
	</div>
<% elsif @current_observation.present? %>
	<div class="row">
		<div class="col-md-6">
			<p>Weather for <%=@current_observation['display_location']['full'] %></p>
			<p><%= @current_observation['temperature_string'] %></p>
			<p>Humidity <%=@current_observation['relative_humidity'] %></p>
			<%= link_to "Full Forecast", @current_observation['forecast_url'], target: "_blank" %>
		</div>
	</div>
<% end %>
<div class="row">
	<div class="col-md-12">
		<h5>Previously searched cities:</h5>
		<ul>
			<% @locations.each do |location| %>
				<li>
					<%= location.city %>, <%= location.state %>
					<%= link_to "More details(including map!)", location_path(id: location.id) %>
					<p>Lat: <%= location.latitude %>, Lon: <%= location.longitude %></p>
					<%= link_to "Full Forecast", "http://www.wunderground.com/US/#{location.state}/#{location.city}.html", target: "_blank" %>	
				</li>
			<% end %>
		</ul>
	</div>
</div>

<script type="text/javascript">
	var cities = [];
	var city = "";
	var state = "";
	var latitude; 
	var longitude;
	<% @locations.each do |location| %>
		city = '<%= location.city %>';
		state = '<%= location.state %>';
		latitude = <%= location.latitude %>;
		longitude = <%= location.longitude %>;
		cities.push([city, state, latitude, longitude]);
	<% end %>
</script>

<div class="row">
	<div class="col-md-12">
		<div id="map-canvas"></div>
	</div>
</div>

<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['google_api_key'] %>&callback=initMap"
    async defer></script>

app/views/welcome/text.html.erb
<h1>Welcome to <%= @current_observation['display_location']['full'] %></h1>
<h3>The current temperature in <%= @current_observation['display_location']['full'] %> is <%= @current_observation['temperature_string'] %></h3>


<p>Find me in app/views/welcome/text.html.erb</p>